lebed_guestbook_homepage:
    pattern:  /{_locale}
    defaults: { _controller: LebedGuestbookBundle:Default:index }
    requirements:
        _locale: en|ru
lebed_guestbook_viewPost:
    pattern: /post/{slug}
    defaults: {_controller: LebedGuestbookBundle:Default:show }
lebed_guestbook_viewMessages:
    pattern: /viewMessages
    defaults: { _controller: LebedGuestbookBundle:Default:viewMessages }
lebed_guestbook_search:
    pattern: /search
    defaults: { _controller: LebedGuestbookBundle:Default:search}
lebed_guestbook_viewPostsOfCategory:
    pattern: /category/{id}
    defaults: { _controller: LebedGuestbookBundle:Default:viewPostsOfCategory}