<?php

namespace Lebed\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    function getIdArrayByName($name)
    {
        return $this->getEntityManager()->createQuery("SELECT m.id FROM LebedGuestbookBundle:Message m WHERE m.message LIKE :name")
            ->setParameter('name', '%'.$name.'%')
            ->getResult();
    }

}